; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Fear & Hunger - Sisyphus MOD"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Twiggy"
#define MyAppExeName "Fear & Hunger Sisyphus MOD.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{AEFBC027-1B01-4297-A19A-AD6B97E894F1}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={localappdata}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
OutputDir=C:\Users\Twiggy\Desktop
OutputBaseFilename=Fear&HungerSisyphusMOD_Setup
SetupIconFile=C:\Users\Twiggy\Desktop\12. Fear & Hunger Sysiphus MOD\www\icon\Sisyphus Icon.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Twiggy\Desktop\12. Fear & Hunger Sysiphus MOD\Fear & Hunger Sisyphus MOD.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Twiggy\Desktop\12. Fear & Hunger Sysiphus MOD\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\Twiggy\Desktop\12. Fear & Hunger Sysiphus MOD\www\icon\Sisyphus Icon.ico"; DestDir: "{app}"; Flags: ignoreversion


[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\Sisyphus Icon.ico"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\Sisyphus Icon.ico"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

